build: off
cache:
    - c:\php7 -> appveyor.yml
    - '%LOCALAPPDATA%\Composer\files -> appveyor.yml'

clone_folder: c:\projects\dibi

services:
    - mssql2012sp1
#    - mssql2014
    - mysql

init:
    - SET PATH=c:\php7;%PATH%
    - SET ANSICON=121x90 (121x90)

install:
    # Install PHP 7.1
    - IF EXIST c:\php7 (SET PHP=0) ELSE (SET PHP=1)
    - IF %PHP%==1 mkdir c:\php7
    - IF %PHP%==1 cd c:\php7
    - IF %PHP%==1 appveyor DownloadFile http://windows.php.net/downloads/releases/archives/php-7.1.5-Win32-VC14-x86.zip
    - IF %PHP%==1 7z x php-7.1.5-Win32-VC14-x86.zip >nul
    - IF %PHP%==1 echo extension_dir=ext >> php.ini
    - IF %PHP%==1 echo extension=php_openssl.dll >> php.ini
    - IF %PHP%==1 appveyor DownloadFile https://files.nette.org/misc/php-sqlsrv.zip
    - IF %PHP%==1 7z x php-sqlsrv.zip >nul
    - IF %PHP%==1 copy SQLSRV\php_sqlsrv_71_ts.dll ext\php_sqlsrv_71_ts.dll
    - IF %PHP%==1 del /Q *.zip

    # Install Nette Tester
    - cd c:\projects\dibi
    - appveyor DownloadFile https://getcomposer.org/composer.phar
    - php composer.phar install --prefer-dist --no-interaction --no-progress

    # Create databases.ini
    - copy tests\databases.appveyor.ini tests\databases.ini

test_script:
    - vendor\bin\tester tests -s -p c:\php7\php -c tests\php-win.ini

on_failure:
    # Print *.actual content
    - type tests\dibi\output\*.actual
